// Auto-generated module: render.js
import { openNew } from "./congress.js";
import { $, $$ } from "./dom.js";
import { icon } from "./icons.js";
import { openLetter } from "./letters.js";
import { A, S, row, save, store } from "./state.js";
import { openEdit, removeTask } from "./tasks.js";
import { clean, dt, esc, id, isSection, noAssignmentNeeded, tableHeading } from "./utils.js";

export function renderLists(){let s=S();s.congregations=clean(s.congregations);s.speakers=clean(s.speakers.concat((s.speakerProfiles||[]).map(p=>p.name)));s.assignmentTypes=clean(s.assignmentTypes);s.assignmentKinds=clean(s.assignmentKinds);$("#congregationDatalist").innerHTML=s.congregations.map(x=>`<option value="${esc(x)}"></option>`).join("");$("#speakerDatalist").innerHTML=s.speakers.map(x=>`<option value="${esc(x)}"></option>`).join("");$("#typeDatalist").innerHTML=s.assignmentTypes.map(x=>`<option value="${esc(x)}"></option>`).join("");$("#kindDatalist").innerHTML=s.assignmentKinds.map(x=>`<option value="${esc(x)}"></option>`).join("")}
export function render(){renderCongresses();renderLists();renderSettings();let c=A();if(!c){/* Раньше после удаления последнего конгресса на экране оставалась таблица заданий уже несуществующего конгресса. */let b=$("#tasksBody");if(b)b.innerHTML="";let t=$("#tableTitle");if(t)t.textContent="";["congressName","congressPlace","congressDate"].forEach(id=>{let el=$("#"+id);if(el)el.value=""});return}$("#congressName").value=c.name;$("#congressPlace").value=c.place||"";$("#congressDate").value=c.date||"";$("#tableTitle").textContent=tableHeading(c);renderTasks()}
export function renderCongresses(){let b=$("#congressList");let series=store.st.series||[];let bySeries={},none=[];store.st.congresses.forEach(c=>{if(c.seriesId&&series.some(s=>s.id===c.seriesId))(bySeries[c.seriesId]=bySeries[c.seriesId]||[]).push(c);else none.push(c)});let cardHTML=c=>`<div class="congress ${c.id===store.st.activeId?"active":""}" data-c="${c.id}"><b>${esc(c.name)}</b><br><small>${esc(c.date||"")}</small></div>`;let html="";series.forEach(s=>{let items=bySeries[s.id]||[];html+=`<div class="series-header"><span>${esc(s.name)}</span><span class="series-actions"><button type="button" class="tiny light icon-text-btn" data-addc="${s.id}" title="Добавить конгресс в эту серию">${icon("plus")}<span>Конгресс</span></button><button type="button" class="tiny danger icon-btn" data-delseries="${s.id}" title="Удалить серию" aria-label="Удалить серию">${icon("trash")}</button></span></div>`;html+=items.length?items.map(cardHTML).join(""):`<p class="hint series-empty">Пока нет конгрессов в этой серии.</p>`});if(none.length){if(series.length)html+=`<div class="series-header"><span>Без серии</span></div>`;html+=none.map(cardHTML).join("")}b.innerHTML=html;$$("#congressList .congress").forEach(d=>d.onclick=()=>{store.st.activeId=d.dataset.c;let c=A();store.sel=c?.tasks[0]?.id||null;save();render()});$$("#congressList [data-addc]").forEach(btn=>btn.onclick=()=>openNew(btn.dataset.addc));$$("#congressList [data-delseries]").forEach(btn=>btn.onclick=()=>{if(!confirm("Удалить серию? Сами конгрессы не удалятся, но перестанут быть частью серии."))return;let sid=btn.dataset.delseries;store.st.congresses.forEach(c=>{if(c.seriesId===sid)c.seriesId=null});store.st.series=store.st.series.filter(s=>s.id!==sid);save();renderCongresses()})}
export function renderSettings(){let s=S();$("#letterLanguage").value=s.language;$("#letterFont").value=s.font;$("#letterFontSize").value=s.fontSize;["senderName","senderCode","senderEmail","senderPhone1","senderPhone2","senderAddress"].forEach(id=>$("#"+id).value=s[id]||"")}
export function peopleHTML(t){let a=(t.participants||[]).filter(p=>p.name||p.congregation);return a.length?a.map(p=>`<div class="participant-line">${esc(p.name||"")}${p.congregation?` <span class="muted">(${esc(p.congregation)})</span>`:""}</div>`).join(""):"<span class='muted'>—</span>"}
export function renderTasks(){let c=A(),b=$("#tasksBody");if(!b)return;b.innerHTML="";if(!c)return;(c.tasks||[]).forEach(t=>{let section=isSection(t);let letterBtn=noAssignmentNeeded(t)?"":`<button type="button" class="tiny icon-btn le" title="Письмо" aria-label="Письмо">${icon("mail")}</button>`;let tr=document.createElement("tr");tr.className=(section?"section-title ":"")+(t.id===store.sel?"selected":"");tr.onclick=e=>{if(e.target.closest("button"))return;store.sel=t.id;renderTasks()};tr.innerHTML=`<td class="time" data-label="Час">${esc(dt(t.time))}</td><td class="num" data-label="№">${esc(t.number)}</td><td class="topic" data-label="Тема">${esc(t.title)}</td><td class="speaker" data-label="Ведучий / Промовець">${peopleHTML(t)}</td><td class="kind" data-label="Інтерв’ю/Показ">${t.kind?`<span class="pill">${esc(t.kind)}</span>`:""}</td><td class="dur" data-label="Хв.">${esc(t.duration)}</td><td class="status-cell" data-label="Статус">${t.status?`<span class="status" data-s="${esc(t.status)}">${esc(t.status)}</span>`:""}</td><td class="mail" data-label="Письмо">${t.letterSent?"✓":""}</td><td class="reh" data-label="Реп.">${t.rehearsal?"✓":""}</td><td class="actions-cell" data-label="Действия"><div class="actgrid"><div class="primary-row"><button type="button" class="tiny icon-btn ed" title="Редактировать" aria-label="Редактировать">${icon("edit")}</button>${letterBtn}</div><button type="button" class="tiny danger icon-btn rm" title="Удалить" aria-label="Удалить">${icon("trash")}</button></div></td>`;b.appendChild(tr);tr.querySelector('.ed').onclick=e=>{e.stopPropagation();openEdit(t.id)};let le=tr.querySelector('.le');if(le)le.onclick=e=>{e.stopPropagation();openLetter(t.id)};tr.querySelector('.rm').onclick=e=>{e.stopPropagation();removeTask(t.id)}})}
